"""Write a baseline-corrected copy of the OpenTouch cache (D1), leaving the raw one intact.

D1 was declined on 2026-08-16 and reinstated on 2026-08-19. The correction is a pure
function of the cache, so this needs no GPU and no re-download: for every clip it removes
that shard's per-taxel baseline plus k sigma, clips at zero, and recomputes F/CoP with the
same maths extract_opentouch.py used, so the two caches are comparable channel for channel.

A NEW DIRECTORY, NEVER IN PLACE. The uncorrected run is the control for what the correction
changed, and a corrected cache written over the raw one would destroy it silently. For the
same reason the harness config is not repointed with a symlink: config_hash is the hash of
the config FILE, so swapping the data underneath a symlink would leave two different
datasets sharing one hash. --write-config emits a sibling config whose only difference is
states_root, and whose hash therefore differs, which is exactly the signal a reader needs.

WHAT IT DOES NOT FIX. The array sits at 95% of full scale with a hard ceiling at 3072 (2026-
08-16), so contact was already clipped at acquisition; removing the baseline recovers the
dynamic range that survived, not the part the sensor threw away.

    python scripts/opentouch/opentouch_apply_baseline.py --cache ~/opentouch/cache \
        --out ~/opentouch/cache_d1 --k 1 --write-config configs/opentouch/eval_harness_d1.yaml
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from src.opentouch import baseline as B                              # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default=os.path.expanduser("~/opentouch/cache"))
    ap.add_argument("--out", default=os.path.expanduser("~/opentouch/cache_d1"))
    ap.add_argument("--k", type=float, default=1.0,
                    help="soft-threshold in units of sigma; 1 = the knee (SESSION_LOG 08-16)")
    ap.add_argument("--write-config", metavar="PATH",
                    help="emit a harness config identical but for states_root")
    ap.add_argument("--keep-maps", action="store_true",
                    help="also write the corrected clip_*.npy (needed by the map arms)")
    a = ap.parse_args()

    rows = B.manifest(a.cache)
    os.makedirs(a.out, exist_ok=True)
    print(f"estimating per-shard baselines over {len(B.by_shard(rows))} shards ...")
    est = B.shard_baselines(a.cache, rows)

    shard_of = {r["idx"]: r.get("shard", "?") for r in rows}
    n_done = n_skip = 0
    f_raw, f_corr = [], []
    for r in rows:
        i = r["idx"]
        src = os.path.join(a.cache, f"clip_{i}.npy")
        sh = shard_of[i]
        if not os.path.exists(src) or sh not in est:
            n_skip += 1
            continue
        base, sigma = est[sh]
        clip = np.load(src)
        corr = B.correct(clip, base, sigma, a.k)
        st = B.moments(corr[:, 0])[:, None, :].astype(np.float32)
        np.save(os.path.join(a.out, f"state_{i}.npy"), st)
        if a.keep_maps:
            np.save(os.path.join(a.out, f"clip_{i}.npy"), corr.astype(np.float16))
        pose = os.path.join(a.cache, f"pose_{i}.npy")
        if os.path.exists(pose):
            shutil.copy2(pose, os.path.join(a.out, f"pose_{i}.npy"))
        f_raw.append(float(np.asarray(clip, np.float64).sum(axis=(1, 2, 3)).mean()))
        f_corr.append(float(st[:, 0, 0].mean()))
        n_done += 1

    with open(os.path.join(a.out, "manifest.jsonl"), "w") as f:
        for r in rows:
            f.write(json.dumps({**r, "d1_k": a.k,
                                "d1": "per-shard per-taxel median + k*sigma, clipped at 0",
                                "has_clip": bool(a.keep_maps) and r.get("has_clip", False)}
                               ) + "\n")

    print(f"wrote {n_done} clips -> {a.out}   (skipped {n_skip} with no raw map)")
    if f_raw:
        print(f"mean F: {np.mean(f_raw):,.0f} -> {np.mean(f_corr):,.0f} "
              f"({np.mean(f_corr) / max(np.mean(f_raw), 1e-9):.2%} of raw)")
        print("The DC that dominated F is gone; what is left is what the ceiling let through.")

    if a.write_config:
        src_cfg = "configs/opentouch/eval_harness.yaml"
        text = open(src_cfg).read()
        old = [l for l in text.splitlines() if "states_root:" in l][0]
        text = text.replace(old, f"  states_root: {a.out}")
        text = text.replace("split_file: data/opentouch_states/splits.json",
                            f"split_file: {a.out}/splits.json")
        text = ("# GENERATED by scripts/opentouch/opentouch_apply_baseline.py -- identical to\n"
                f"# {src_cfg} except states_root, which points at the D1-corrected cache\n"
                f"# (k={a.k}). The hash therefore differs from the raw harness, which is the\n"
                "# point: it is a different protocol instance, not the same one re-run.\n"
                + text)
        os.makedirs(os.path.dirname(a.write_config) or ".", exist_ok=True)
        with open(a.write_config, "w") as f:
            f.write(text)
        print(f"wrote {a.write_config}")


if __name__ == "__main__":
    raise SystemExit(main())
