"""Rebuild docs/skill_comparison.md from the runs' own CSVs.

Every number in that document is read from the table the run wrote, because the alternative
-- copying figures across by hand as runs accumulate -- is how a superseded number outlives
the run that produced it. Six OpenTouch runs and two ActionSense families is already past
the point where that stays reliable.

WHICH SKILL. The driver's frame-pooled SS_vs_persistence, averaged over folds. The report
script's per-clip-equal-weight `skill` is a DIFFERENT estimator and disagrees (ar on F: 0.367
against 0.302); the two must not be mixed in one table. Frame-pooled is used here because it
is what every run wrote and what the predictability ceiling is computed over.

    python scripts/shared/build_skill_comparison.py [--out docs/skill_comparison.md]
"""
from __future__ import annotations

import argparse
import collections
import csv
import os

CH = ["F_R", "CoPx_R", "CoPy_R"]

# (label, ActionSense model name, OpenTouch model name). None means the arm has no
# counterpart there -- NOT that it scored zero.
ROWS = [("AR", "ar", "ar"),
        ("seasonal", "seasonal", "seasonal"),
        # ActionSense's probGRU predicts the FAST component against persistence-of-fast,
        # OpenTouch's predicts the RAW target under the harness. Same name, different
        # question, so the ActionSense side stays empty rather than inviting the comparison.
        ("probGRU", None, "prob_gru"),
        ("GRU-aggregate", "aggregate", "map_aggregate"),
        ("CNN (map)", "cnn", "cnn"),
        ("flatten (map)", "flatten", "flatten")]

# d1_map (08-22) is absent on purpose: flatten and cnn predicted arrays of zeros in it.
RUNS = [("raw", "08-17", "4-fold, location held out, uncorrected target",
         "docs/opentouch/raw/opentouch_cv4.csv"),
        ("df", "08-18", "adds dF/dt to the probGRU input",
         "docs/opentouch/df/opentouch_cv4_df.csv"),
        ("d1", "08-20", "**D1 baseline correction**, weights on val NLL",
         "docs/opentouch/d1/opentouch_cv4_d1.csv"),
        ("d1_mse", "08-21", "weights on val MSE instead",
         "docs/opentouch/d1_mse/opentouch_cv4_d1_mse.csv"),
        ("d1_map2", "08-23", "the three map encoders, `--baseline-scope shard`",
         "docs/opentouch/d1_map2/opentouch_cv4_d1_map2.csv"),
        ("d1_map3", "08-24", "`d1_map2` repeated to save checkpoints",
         "docs/opentouch/d1_map3/opentouch_cv4_d1_map3.csv")]


def opentouch(path):
    a = collections.defaultdict(list)
    for r in csv.DictReader(open(path)):
        if r["horizon_step"] == "all" and r["metric"] == "SS_vs_persistence":
            a[(r["model"], r["channel"])].append(float(r["value"]))
    return {k: sum(v) / len(v) for k, v in a.items()}


def actionsense(root="docs/actionsense"):
    """The frozen harness for ar/seasonal, and the tactile_map CV at its longest history."""
    out = collections.defaultdict(list)
    p = os.path.join(root, "harness_baselines.csv")
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            if (r["horizon_step"] == "all" and r["metric"] == "SS_vs_persistence"
                    and r["channel"] in CH):
                out[(r["model"], r["channel"])].append(float(r["value"]))
    for f in ("tactile_map_cv_results.csv", "tactile_map_cv_results_aggregate.csv"):
        p = os.path.join(root, f)
        if not os.path.exists(p):
            continue
        for r in csv.DictReader(open(p)):
            if r.get("history_s") != "10":          # its best history; see SESSION_LOG 08-20
                continue
            for c in CH:
                if r.get(f"{c}_skill"):
                    out[(r["encoder"], c)].append(float(r[f"{c}_skill"]))
    return {k: sum(v) / len(v) for k, v in out.items()}


def cell(tbl, model, ch):
    v = tbl.get((model, ch)) if model else None
    return "—" if v is None else f"{v:.3f}".replace("-", "−")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/skill_comparison.md")
    a = ap.parse_args()

    AS = actionsense()
    OT = {n: opentouch(p) for n, _, _, p in RUNS if os.path.exists(p)}
    missing = [n for n, _, _, p in RUNS if not os.path.exists(p)]
    if missing:
        print(f"note: no CSV for {', '.join(missing)} -- their columns will be empty")

    L = ["# Skill against persistence — every run, both sensors", "",
         "Skill = 1 − MSE(model)/MSE(persistence) at the full 1 s horizon, pooled over",
         "frames, averaged over folds. Right hand only: OpenTouch instruments one hand, so",
         "ActionSense's `_R` channels are the closest its two-handed target allows.", "",
         "Generated by `scripts/shared/build_skill_comparison.py` — every number is read from the",
         "run's own CSV, never transcribed. Rerun it after any new run.", "",
         "## The runs", "",
         "| run | date | what changed | arms |", "|---|---|---|---|"]
    for n, date, what, path in RUNS:
        arms = ", ".join(sorted({m for m, _ in OT.get(n, {})} - {"persistence"})) or "—"
        L.append(f"| `{n}` | {date} | {what} | {arms} |")
    L += ["",
          "`d1_map` (08-22) is **excluded**: flatten and cnn predicted arrays of zeros there.",
          "See SESSION_LOG 2026-08-22.", ""]

    for ch in CH:
        L += [f"## {ch}", "",
              "| model | ActionSense | " + " | ".join(f"`{n}`" for n, *_ in RUNS) + " |",
              "|---" * (len(RUNS) + 2) + "|"]
        for label, asn, otn in ROWS:
            cells = [cell(AS, asn, ch)] + [cell(OT.get(n, {}), otn, ch) for n, *_ in RUNS]
            L.append(f"| {label} | " + " | ".join(cells) + " |")
        L.append("")

    L += open("docs/_skill_comparison_notes.md").read().rstrip().split("\n") + [""]
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out} ({len(RUNS)} runs x {len(ROWS)} models x {len(CH)} channels)")


if __name__ == "__main__":
    raise SystemExit(main())
